# Generated by Django 3.2.4 on 2021-06-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=300, null=True)),
                ('min_players', models.PositiveSmallIntegerField(default=1)),
                ('max_players', models.PositiveSmallIntegerField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('min_age', models.PositiveSmallIntegerField(default=0)),
                ('game_type', models.CharField(choices=[('educational', 'Educational'), ('euro', 'Euro'), ('cards', 'Cards'), ('rpg', 'Rpg')], max_length=50)),
                ('designers', models.ManyToManyField(related_name='games', to='games.Designers')),
            ],
        ),
    ]
