# Generated by Django 3.2.4 on 2021-06-15 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('description', models.TextField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=300, null=True)),
                ('min_players', models.PositiveSmallIntegerField(default=1)),
                ('max_players', models.PositiveSmallIntegerField(null=True)),
                ('duration', models.PositiveIntegerField(default=15, null=True)),
                ('min_age', models.PositiveSmallIntegerField(default=0)),
                ('game_type', models.CharField(choices=[('educational', 'Educational'), ('euro', 'Euro'), ('cards', 'Cards'), ('rpg', 'Rpg')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameDesigners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_designers', to='games.designers')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_designers', to='games.game')),
            ],
            options={
                'unique_together': {('game', 'designers')},
            },
        ),
        migrations.AddField(
            model_name='game',
            name='designer',
            field=models.ManyToManyField(through='games.GameDesigners', to='games.Designers'),
        ),
        migrations.AddField(
            model_name='designers',
            name='games',
            field=models.ManyToManyField(blank=True, through='games.GameDesigners', to='games.Game'),
        ),
    ]
