# Generated by Django 3.2.4 on 2021-06-14 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDesigners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_designers', to='games.designers')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_designers', to='games.game')),
            ],
            options={
                'unique_together': {('game', 'designers')},
            },
        ),
    ]
