# Generated by Django 3.2.4 on 2021-06-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
