version: '3.4'

services:
  toxogos_api:
    build:
      context: .
    image: toxogos_api
    container_name: toxogos_api
    volumes:
      - .:/app
    ports:
      - "8800:8000"
    env_file:
      - ./settings.env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    image: toxogos_frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8880:8880"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./settings.env
